#### Run the Flumina pipeline first to obtain variant calls in VCF files.
#### Then run convertVCFtoTable.R to create a VCF table and place it at
#### `vcftable.path` below.

# Required packages:
# 1. data.table
# 2. foreach
# 3. doParallel
# 4. snow
# 5. seqinr

# Runtime is approximately five minutes for 500 samples.

args = commandArgs(trailingOnly = TRUE)
# args = "config.cfg"  # Use a local configuration file during development.

# args = "config.cfg"  # Use a local configuration file during development.
# Function to read and parse configuration file
lines <- readLines(args)

# Parse key-value pairs into a named list.
config <- list()
for (line in lines) {
  line <- trimws(line)  # Remove leading and trailing whitespaces
  if (nchar(line) != 0 && !startsWith(line, "#")) {  # Ignore empty lines and comments
    parts <- strsplit(line, "=")[[1]]
    if (length(parts) == 2) {
      key <- trimws(parts[1])
      value <- trimws(parts[2])
      config[[key]] <- value
    }# end if
  } # End of if block.
} # End of for loop.

# Define these parameters.

# Output directory used by convertVCFtoTable.R.
output.directory = paste0(gsub("\"", "", config$OUTPUT_DIRECTORY), "/variant_analysis")

# File name, or path, of the table generated by convertVCFtoTable.R.
vcftable.path = paste0(output.directory, "/variant-table.csv")

# Reference used for variant calling; provide the full path when it is not in the
# working directory.
reference.path = paste0(gsub("\"", "", config$OUTPUT_DIRECTORY),"/reference.fa")

# Optional metadata file for joining to the amino-acid data; set to NULL when
# unavailable.
metadata.file = gsub("\"", "", config$METADATA)
if(length(metadata.file) == 0L || metadata.file == "NULL") {
  metadata.file <- NULL
}

# Configure multithreading and memory usage.
threads = as.numeric(gsub("\"", "", config$THREADS))

# Config helper with defaults (returns `default` when the key is missing/blank/NULL).
# Robust to interactive runs where the config file was not parsed into `config`.
if (!exists("config") || !is.list(config)) config = list()
cfg = function(key, default = NULL){
  v = config[[key]]
  if (is.null(v)) return(default)
  v = gsub("\"", "", trimws(v))
  if (!nzchar(v) || v == "NULL") return(default)
  v
}

# Depth-artifact guards applied to the combined amino-acid table (see below).
# MIN_DEPTH defaults to 100x: at low template input LoFreq/GATK4 report false
# fixations (founder/jackpot effect), so a real depth floor is enforced by
# default even if a study omits the key. MIN_QUALITY defaults off (0).
# DEDUP_KEYS is opt-in: a comma-separated list of metadata columns identifying
# one biological sample (e.g. "Animal.ID,DPI,Quarter"); when set, replicate
# libraries of the same sample are collapsed by keeping the deepest call per
# sample x locus x position x alternative. Unset -> no dedup (default).
min.depth   = as.numeric(cfg("MIN_DEPTH", "100"))
min.quality = as.numeric(cfg("MIN_QUALITY", "0"))
dedup.keys  = cfg("DEDUP_KEYS", "")

# output.directory = "/Users/chutter/Dropbox/Research/1_Main-Projects/0_Working-Projects/Bird_Flu/bird_flu_new/variant_analysis"
# vcftable.path = paste0(output.directory, "/variant-table.csv")
# reference.path = paste0("/Users/chutter/Dropbox/Research/1_Main-Projects/0_Working-Projects/Bird_Flu/bird_flu_new/Reference/reference.fa")
# threads = 4
# metadata.file = NULL

#############################################
#### Should not need to modify below here
#############################################

# Set the working directory and create the output directory.
dir.create(paste0(output.directory, "/aa_db"))
require(foreach)

# Coding intervals for every product, shared with convertVCFtoTable.R to keep gene
# start positions consistent.
script.dir = dirname(sub("^--file=", "",
                         grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)[1]))
if (is.na(script.dir) || !nzchar(script.dir)) script.dir = "."
source(file.path(script.dir, "fluORFs.R"))

# Collect the per-sample input tables.
reference = flu_read_fasta(reference.path)

# `na.strings = ""` is required here. The neuraminidase gene is called "NA", so
# read.csv's default converts every neuraminidase row's `product` (and, after
# shortening, its `locus`) to a missing value and removes the entire segment.
# outputSummary.R reads the amino-acid table with the same setting for exactly
# this reason.
vcf.data = read.csv(vcftable.path, header = TRUE, na.strings = "")
# Sanitize character columns to prevent "invalid multibyte string" errors in
# `%dopar%`.
for (col in names(vcf.data)) {
  if (is.character(vcf.data[[col]])) {
    vcf.data[[col]] = iconv(vcf.data[[col]], to = "UTF-8", sub = "")
  } else if (is.factor(vcf.data[[col]])) {
    vcf.data[[col]] = factor(iconv(as.character(vcf.data[[col]]), to = "UTF-8", sub = ""), levels = unique(iconv(levels(vcf.data[[col]]), to = "UTF-8", sub = "")))
  }
}
sample.names = unique(vcf.data$sample)

# Older variant tables have no `product` column. Rather than silently translate
# them in the wrong frame, annotate them here the same way convertVCFtoTable.R
# now does.
if (!"product" %in% colnames(vcf.data)){
  message("variant-table.csv predates per-product annotation; annotating now.")
  vcf.data = flu_annotate_positions(vcf.data, reference,
                                    locus.col = "locus", pos.col = "position")
}

# The spliced coding sequence for every product, built once.
#
# This implementation corrects a previous bug where codons were extracted directly
# from the segment based on the formula `(aa_position-1)*3+1`. That approach
# incorrectly assumed all coding sequences (CDS) were contiguous and began at 
# nucleotide 1. For spliced products such as M2, NEP, and PA-X, this extracted
# out-of-frame codons or translated beyond the stop codon (for example, M1 and
# NS1), generating incorrect amino-acid predictions. Indexing the properly spliced
# CDS accurately accommodates these junctions.
cds.lookup = list()
for (lc in names(reference)){
  for (o in flu_orfs(lc, nchar(reference[[lc]])))
    cds.lookup[[paste(lc, o$gene, sep = "|")]] = flu_cds_seq(o, reference[[lc]])
}

# One translation unit per (segment, product) pair present in the data.
gene.keys = unique(vcf.data[, c("locus", "product")])
gene.keys = gene.keys[!is.na(gene.keys$product), , drop = FALSE]

# Sets up multiprocessing
my.cluster = parallel::makeCluster(threads, type = "PSOCK")
doParallel::registerDoParallel(cl = my.cluster)

# Loop for CD-HIT-EST reductions.
foreach::foreach(i = seq_along(sample.names), .packages = c("foreach", "seqinr", "data.table")) %dopar% {

#for (i in 1:length(sample.names)){
  # Subset the data for the current sample.
  sample.data = vcf.data[vcf.data$sample %in% sample.names[i],]

  # Iterate over each (segment, product) pair to assess amino-acid changes.
  new.gene = c()
  for (j in seq_len(nrow(gene.keys))){

    # Initialize columns for the derived variables.
    gene.data = sample.data[sample.data$locus   %in% gene.keys$locus[j] &
                            sample.data$product %in% gene.keys$product[j], ]

    if (nrow(gene.data) == 0){ next }

    gene.data$reference_codon = "NA"
    gene.data$alternative_codon = "NA"
    gene.data$reference_aa = "NA"
    gene.data$alternative_aa = "NA"
    gene.data$aa_changing = "NA"

    # Use the spliced CDS for this product; codons are indexed into it rather
    # than into the complete segment.
    ref.cds = cds.lookup[[paste(gene.keys$locus[j], gene.keys$product[j], sep = "|")]]
    if (is.null(ref.cds)){ new.gene = rbind(new.gene, gene.data); next }

    # Translate each variant in the product data.
    for (k in 1:nrow(gene.data)){

      # A position outside a coding region has no codon. Retain `NA` rather than
      # fabricating an amino-acid position.
      cds.pos = gene.data$cds_position[k]
      aa.pos  = gene.data$aa_position[k]
      if (is.na(cds.pos) || is.na(aa.pos)) next

      # Substitute the alternative base at its CDS index.
      alt.cds = ref.cds
      substr(alt.cds, cds.pos, cds.pos) = as.character(gene.data$alternative[k])

      # Extract the codon from the spliced CDS.
      cod.start = (aa.pos - 1) * 3 + 1
      gene.data$reference_codon[k]   = substr(ref.cds, cod.start, cod.start + 2)
      gene.data$alternative_codon[k] = substr(alt.cds, cod.start, cod.start + 2)

      # A truncated terminal codon cannot be translated.
      if (nchar(gene.data$reference_codon[k]) < 3) next

      # Translate the codon.
      gene.data$reference_aa[k] = as.character(seqinr::translate(unlist(strsplit(gene.data$reference_codon[k], ""))))
      gene.data$alternative_aa[k] = as.character(seqinr::translate(unlist(strsplit(gene.data$alternative_codon[k], ""))))

      # Determine whether the amino acid changed.
      if (gene.data$reference_aa[k] == gene.data$alternative_aa[k]){
        gene.data$aa_changing[k] = "NO"
      } else { gene.data$aa_changing[k] = "YES"}

    }#end k

    # Store the annotated variants.
    new.gene = rbind(new.gene, gene.data)

  }# end j loop

  # Write the data for the current sample.
  write.csv(new.gene, paste0(output.directory, "/aa_db/", sample.names[i], ".csv"),
            row.names = F, quote = F)

}# End of i loop.
  
parallel::stopCluster(cl = my.cluster)


#########################
###### Create a combined table
#########################

# Join metadata when it is available.
if (is.null(metadata.file) != TRUE){
  meta.sample = read.csv(metadata.file)
} # End of if block.

# List the sample files.
aa.sample = list.files(paste0(output.directory, "/aa_db"))

# Combine all individual sample tables.
all.samples = c()
## Retain and report valid variants whose samples are absent from the metadata
## CSV, rather than dropping them during the merge below.
samples.without.metadata = c()
for (i in seq_along(aa.sample)){
  
  # Ensure `na.strings = ""` so that "NA" gene names are not parsed as missing
  # data.
  sample.data = read.csv(paste0(output.directory, "/aa_db/", aa.sample[i]),
                         header = TRUE, sep = ",", na.strings = "")
  
  # Combine metadata when it is available.
  if (is.null(metadata.file) != TRUE){
    # Perform a LEFT join (all.x = TRUE) to retain all variant records.
    #
    # Using an INNER join (all = FALSE) would silently discard all variant calls
    # for samples not listed in the metadata CSV, leading to unintended data loss.
    # The absence of a metadata record should not invalidate the sequencing results.
    # Retaining these calls with `NA` metadata values preserves the variants while
    # accurately representing the missing metadata.
    if (nrow(sample.data) > 0 && !(sample.data$sample[1] %in% meta.sample$Sample)){
      samples.without.metadata = c(samples.without.metadata, sample.data$sample[1])
    }
    sample.data = merge(sample.data, meta.sample, by.x = "sample", by.y = "Sample",
                        all.x = TRUE)
  } # End of if block.
  
  sample.data$locus = gsub("^A_", "", sample.data$locus)
  sample.data$locus = gsub("_[A-Z][0-9]+$", "", sample.data$locus)
  all.samples = rbind(all.samples, sample.data)
} # End of i loop.

# Log a warning for samples that were retained with NA metadata. Note that downstream
# analyses or grouping operations dependent on metadata columns may exclude these records.
if (length(samples.without.metadata) > 0){
  cat(sprintf("METADATA: %d sample(s) have no row in %s and were kept with NA metadata: %s\n",
              length(samples.without.metadata), basename(metadata.file),
              paste(samples.without.metadata, collapse = ", ")))
  warning(sprintf("%d sample(s) absent from the metadata CSV: %s. Their calls are KEPT ",
                  length(samples.without.metadata),
                  paste(samples.without.metadata, collapse = ", ")),
          "with NA metadata; add them to the CSV if they should be grouped.")
}

#############################################
#### Depth-artifact guards (depth/quality floor + optional swab dedup)
#############################################
# Low-input libraries can produce spurious apparent fixations through founder or
# jackpot effects. Enforce a read-depth floor so the amino-acid table and all
# downstream high-frequency or curated analyses remain clean.
all.samples$depth   = suppressWarnings(as.numeric(all.samples$depth))
all.samples$quality = suppressWarnings(as.numeric(all.samples$quality))
n0 = nrow(all.samples)
all.samples = all.samples[!is.na(all.samples$depth) & all.samples$depth >= min.depth, ]
if (min.quality > 0){
  all.samples = all.samples[!is.na(all.samples$quality) & all.samples$quality >= min.quality, ]
}
cat(sprintf("Depth/quality filter (MIN_DEPTH=%s, MIN_QUALITY=%s): %d -> %d calls\n",
            min.depth, min.quality, n0, nrow(all.samples)))

# Optional swab deduplication: collapse replicate libraries from the same
# biological sample by retaining the deepest call for each DEDUP_KEYS × locus ×
# position × alternative combination. Disabled unless DEDUP_KEYS is configured.
if (nzchar(dedup.keys)){
  keys = trimws(strsplit(dedup.keys, ",")[[1]])
  miss = setdiff(keys, colnames(all.samples))
  if (length(miss) > 0){
    warning("DEDUP_KEYS column(s) not found (", paste(miss, collapse = ", "),
            "); skipping swab dedup.")
  } else {
    n1 = nrow(all.samples)
    all.samples = all.samples[order(-all.samples$depth), ]
    # `product` belongs in the key: one nucleotide can code in two reading
    # frames, so (locus, position, alternative) alone would merge a PA row with
    # its PA-X counterpart and discard a valid annotation.
    dedup.cols = c(keys, "locus", "product", "position", "alternative")
    dedup.cols = dedup.cols[dedup.cols %in% colnames(all.samples)]
    dup.key = do.call(paste, c(all.samples[, dedup.cols], sep = "|"))
    all.samples = all.samples[!duplicated(dup.key), ]
    cat(sprintf("Swab dedup on [%s + locus/position/alternative]: %d -> %d calls\n",
                paste(keys, collapse = ","), n1, nrow(all.samples)))
  }
}

# Save the complete tab-delimited amino-acid table.
write.table(all.samples, paste0(output.directory, "/all_sample_amino_acids.txt"),
            row.names = F, quote = F, sep = "\t")


#########################
###### End of script
#########################


